import { Saira, Anta, Oxanium, Orbitron, Sansation } from "next/font/google";
import "./globals.css";
import ToastProvider from "./Components/ToastProvider";
import ClientProvider from "./ClientProvider";
import NavbarWrapper from "./Components/NavbarWrapper";

// const saira = Saira({
//   subsets: ["latin-ext"],
//   variable: "--font-saira",
//   weight: ["500"],
// });

// const anta = Anta({
//   subsets: ["latin"],
//   variable: "--font-anta",
//   weight: ["400"],
// });

// const oxanium = Oxanium({
//   subsets: ["latin"],
//   variable: "--font-oxanium",
//   weight: ["600"],
// });
// const orbitron = Orbitron({
//   subsets: ["latin"],
//   variable: "--font-oxanium",
//   weight: ["400"],
// });
const sansation = Sansation({
  subsets: ["latin"],
  variable: "--font-oxanium",
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sansation.className} antialiased`}>
        <ClientProvider>
          <NavbarWrapper />

          {children}
          <ToastProvider />
        </ClientProvider>
      </body>
    </html>
  );
}
